
server:
  port: 8080
  servlet:
    context-path: /phone-store

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/phone_store?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: Aa123456
    type: com.alibaba.druid.pool.DruidDataSource
    hikari:
      maximum-pool-size: 25
      minimum-idle: 5
      idle-timeout: 30000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy/MM/dd HH:mm:ss

#logging:
#  level: error
#  file:
#    name: log.log
#  charset:
#    console: GBK
#    file: GBK
